In [ ]:
import torch

In [ ]:
# function with information about tensor
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/Size: {}".format(x.shape))
    print("Values: \n{}".format(x))

1.Создайте двумерный тензор, после чего добавьте в него новое измерение размером 1 перед измерением 0:

In [ ]:
x = torch.Tensor (5,6)
x_unsq= torch.unsqueeze(x, 0)
x_unsq.shape, x.shape

(torch.Size([1, 5, 6]), torch.Size([5, 6]))

In [ ]:

# second variant
y = torch.Tensor (2,3)
y_unsq= torch.reshape(y, (1,2,3))
y_unsq.shape, y.shape

(torch.Size([1, 2, 3]), torch.Size([2, 3]))

2. Удалите дополнительное измерение, которое вы создали в шаге 1:

In [ ]:
x_old_shape = torch.squeeze(x_unsq)
x_old_shape.shape

torch.Size([5, 6])

In [ ]:
y_old_shape = torch.reshape(y_unsq, (2,3))
y_old_shape.shape

torch.Size([2, 3])

3. Создайте случайный тензор формы 5 на 3 в интервале [3, 7):

In [ ]:

# usually dtype is torch.float64, but in this case it's too much
y = torch.randint(3,7,(5,3), dtype = torch.float32)
describe (y)

Type: torch.FloatTensor
Shape/Size: torch.Size([5, 3])
Values: 
tensor([[3., 6., 4.],
        [4., 3., 3.],
        [3., 3., 5.],
        [3., 5., 4.],
        [3., 4., 5.]])


4. Создайте тензор со значениями, взятыми из нормального распределения (матожидание = 0, стандартное отклонение = 1):

In [ ]:
z = torch.randn (3,2)
describe (z)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 2])
Values: 
tensor([[-1.2043, -1.0971],
        [ 0.3915,  0.5150],
        [ 0.3566, -0.4827]])


5. Извлеките индексы всех ненулевых элементов из тензора torch.Tensor([1, 1, 1, 0, 1]):

In [ ]:
a = torch.Tensor([1, 1, 1, 0, 1])
torch.argwhere(a)

tensor([[0],
        [1],
        [2],
        [4]])

6. Создайте случайный тензор размерности (3, 1) а затем горизонтально разместите в ряд четыре его копии:

In [ ]:
# may be I didn't get task
c = torch.Tensor (3,1)
torch.stack((c, c, c, c), dim=0)

tensor([[[-9.6144e+23],
         [ 3.3351e-41],
         [-1.1231e+21]],

        [[-9.6144e+23],
         [ 3.3351e-41],
         [-1.1231e+21]],

        [[-9.6144e+23],
         [ 3.3351e-41],
         [-1.1231e+21]],

        [[-9.6144e+23],
         [ 3.3351e-41],
         [-1.1231e+21]]])

In [ ]:
torch.column_stack((c,c,c,c))

tensor([[-9.6144e+23, -9.6144e+23, -9.6144e+23, -9.6144e+23],
        [ 3.3351e-41,  3.3351e-41,  3.3351e-41,  3.3351e-41],
        [-1.1231e+21, -1.1231e+21, -1.1231e+21, -1.1231e+21]])

In [ ]:
torch.hstack((c,c,c,c))

tensor([[-9.6144e+23, -9.6144e+23, -9.6144e+23, -9.6144e+23],
        [ 3.3351e-41,  3.3351e-41,  3.3351e-41,  3.3351e-41],
        [-1.1231e+21, -1.1231e+21, -1.1231e+21, -1.1231e+21]])

7. Верните пакетное произведение 2 трехмерных матриц (a = torch.rand(3,4,5) и b = torch.rand(3, 5, 4)):

In [ ]:
a = torch.rand(3,4,5)
b = torch.rand(3,5,4)
C = torch.matmul(a,b)
describe (C)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 4, 4])
Values: 
tensor([[[1.0724, 0.9845, 1.5613, 1.3095],
         [0.7124, 0.5166, 1.2038, 1.0557],
         [1.0348, 0.8634, 1.7679, 1.4277],
         [0.9797, 0.8091, 2.2743, 1.6518]],

        [[1.0248, 1.1648, 0.6054, 1.5336],
         [1.1093, 1.0623, 0.5347, 1.7105],
         [1.5998, 0.8834, 0.4558, 1.8331],
         [0.9649, 0.5394, 0.1784, 1.6282]],

        [[1.5148, 1.7013, 1.6181, 1.2633],
         [0.4467, 0.5699, 0.5125, 0.2371],
         [1.6949, 2.0466, 2.0332, 1.4436],
         [1.1262, 1.3427, 1.0156, 1.0516]]])


8. Верните пакетное произведение трехмерной и двумерной матриц (a = torch.rand(3, 4, 5) и b = torch.rand(5,4)):

In [ ]:
a = torch.rand (3,4,5)
b = torch.rand (5,4)
c = torch.matmul (a,b)
describe (c)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 4, 4])
Values: 
tensor([[[0.5444, 0.7782, 1.0330, 0.8043],
         [0.4604, 0.5547, 0.9465, 0.7961],
         [0.5338, 0.6727, 0.9580, 1.2230],
         [1.1972, 1.5046, 0.8103, 1.2091]],

        [[0.8018, 1.1518, 0.7169, 1.5613],
         [0.8201, 1.1739, 1.3037, 0.9511],
         [0.5130, 0.6354, 1.1580, 0.5983],
         [0.8970, 1.1209, 1.2721, 1.3709]],

        [[0.6890, 1.0109, 1.4340, 1.1387],
         [0.9834, 1.2859, 0.7017, 1.2220],
         [1.0940, 1.1900, 1.3641, 1.1579],
         [0.6485, 0.8174, 0.8199, 1.2528]]])
