In [23]:
import torch

In [24]:
# function with information about tensor
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/Size: {}".format(x.shape))
    print("Values: \n{}".format(x))

1.Создайте двумерный тензор, после чего добавьте в него новое измерение размером 1 перед измерением 0:

In [25]:
x = torch.Tensor (5,6)
x_unsq= torch.unsqueeze(x, 0)
x_unsq.shape, x.shape

(torch.Size([1, 5, 6]), torch.Size([5, 6]))

In [26]:

# second variant
y = torch.Tensor (2,3)
y_unsq= torch.reshape(y, (1,2,3))
y_unsq.shape, y.shape

(torch.Size([1, 2, 3]), torch.Size([2, 3]))

2. Удалите дополнительное измерение, которое вы создали в шаге 1:

In [ ]:
x_old_shape = torch.squeeze(x_unsq)
x_old_shape.shape

torch.Size([5, 6])

In [ ]:
y_old_shape = torch.reshape(y_unsq, (2,3))
y_old_shape.shape

torch.Size([2, 3])

3. Создайте случайный тензор формы 5 на 3 в интервале [3, 7):

In [ ]:

# usually dtype is torch.float64, but in this case it's too much
y = torch.randint(3,7,(5,3), dtype = torch.float32)
describe (y)

Type: torch.FloatTensor
Shape/Size: torch.Size([5, 3])
Values: 
tensor([[5., 3., 6.],
        [4., 4., 5.],
        [3., 5., 3.],
        [5., 5., 6.],
        [3., 5., 5.]])


4. Создайте тензор со значениями, взятыми из нормального распределения (матожидание = 0, стандартное отклонение = 1):

In [ ]:
z = torch.randn (3,2)
describe (z)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 2])
Values: 
tensor([[-0.4846, -1.7859],
        [ 2.2988, -1.0864],
        [ 1.5554, -0.2712]])


5. Извлеките индексы всех ненулевых элементов из тензора torch.Tensor([1, 1, 1, 0, 1]):

In [ ]:
a = torch.Tensor([1, 1, 1, 0, 1])
torch.argwhere(a)

tensor([[0],
        [1],
        [2],
        [4]])

6. Создайте случайный тензор размерности (3, 1) а затем горизонтально разместите в ряд четыре его копии:

In [ ]:
# may be I didn't get task
c = torch.Tensor (3,1)
torch.stack((c, c, c, c), dim=1)

tensor([[[-1.1503e+26],
         [-1.1503e+26],
         [-1.1503e+26],
         [-1.1503e+26]],

        [[ 4.4585e-41],
         [ 4.4585e-41],
         [ 4.4585e-41],
         [ 4.4585e-41]],

        [[ 1.4412e-07],
         [ 1.4412e-07],
         [ 1.4412e-07],
         [ 1.4412e-07]]])

In [ ]:
torch.column_stack((c,c,c,c))

tensor([[-1.1503e+26, -1.1503e+26, -1.1503e+26, -1.1503e+26],
        [ 4.4585e-41,  4.4585e-41,  4.4585e-41,  4.4585e-41],
        [ 1.4412e-07,  1.4412e-07,  1.4412e-07,  1.4412e-07]])

In [ ]:
torch.hstack((c,c,c,c))

tensor([[-1.1503e+26, -1.1503e+26, -1.1503e+26, -1.1503e+26],
        [ 4.4585e-41,  4.4585e-41,  4.4585e-41,  4.4585e-41],
        [ 1.4412e-07,  1.4412e-07,  1.4412e-07,  1.4412e-07]])

In [ ]:
torch.cat ([c,c,c,c], dim = 1)

tensor([[-1.1503e+26, -1.1503e+26, -1.1503e+26, -1.1503e+26],
        [ 4.4585e-41,  4.4585e-41,  4.4585e-41,  4.4585e-41],
        [ 1.4412e-07,  1.4412e-07,  1.4412e-07,  1.4412e-07]])

7. Верните пакетное произведение 2 трехмерных матриц (a = torch.rand(3,4,5) и b = torch.rand(3, 5, 4)):

In [ ]:
a = torch.rand(3,4,5)
b = torch.rand(3,5,4)
C = torch.matmul(a,b)
describe (C)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 4, 4])
Values: 
tensor([[[0.2259, 0.5976, 0.8414, 0.8702],
         [0.5908, 0.4892, 1.1822, 1.1992],
         [0.2508, 0.3486, 1.1892, 0.8381],
         [0.4030, 0.5799, 1.1843, 1.1851]],

        [[1.9803, 1.1486, 1.8827, 2.0979],
         [0.8718, 0.4804, 0.9706, 1.0429],
         [1.2473, 0.9131, 1.3927, 1.3190],
         [0.7207, 0.1399, 0.3361, 0.6288]],

        [[1.6176, 1.4643, 1.6474, 1.1580],
         [1.2480, 1.4684, 1.3846, 1.7952],
         [1.6359, 1.9552, 1.6972, 2.0024],
         [1.2906, 1.2340, 1.5479, 1.5589]]])


8. Верните пакетное произведение трехмерной и двумерной матриц (a = torch.rand(3, 4, 5) и b = torch.rand(5,4)):

In [ ]:
a = torch.rand (3,4,5)
b = torch.rand (5,4)
c = torch.matmul (a,b)
describe (c)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 4, 4])
Values: 
tensor([[[1.1546, 1.5919, 1.2024, 1.1278],
         [1.0953, 1.1244, 1.0536, 0.8739],
         [1.5533, 1.5549, 1.1788, 1.3144],
         [1.5507, 1.3686, 0.9014, 1.2373]],

        [[1.4336, 1.2374, 0.6886, 1.2082],
         [1.5109, 1.9117, 1.3349, 1.2885],
         [0.8433, 0.7837, 0.6098, 0.6624],
         [1.1839, 1.1843, 0.4480, 0.9144]],

        [[1.1622, 1.3923, 1.2527, 1.0964],
         [0.9991, 0.7556, 0.6052, 0.9343],
         [1.9065, 1.6421, 1.2626, 1.6101],
         [0.6416, 0.7677, 0.4797, 0.5499]]])


Вторая часть практики.

1. Создайте случайный тензор размерности (7,7):

In [ ]:
x_tensor = torch.rand(7,7)
describe (x_tensor)

Type: torch.FloatTensor
Shape/Size: torch.Size([7, 7])
Values: 
tensor([[0.0686, 0.5463, 0.5042, 0.2738, 0.4232, 0.9730, 0.3036],
        [0.9187, 0.9310, 0.2783, 0.1718, 0.9656, 0.2147, 0.8593],
        [0.3064, 0.0964, 0.5338, 0.6507, 0.2671, 0.3866, 0.3199],
        [0.9409, 0.9522, 0.9083, 0.0786, 0.1912, 0.8358, 0.8804],
        [0.0547, 0.5517, 0.1912, 0.3017, 0.5367, 0.4528, 0.0510],
        [0.2689, 0.1912, 0.5799, 0.5656, 0.9758, 0.6505, 0.7831],
        [0.7799, 0.3099, 0.0904, 0.3491, 0.0769, 0.4252, 0.0384]])


2. Определите операцию матричного умножения на тензоре с шага 1 с любым случайным тензором с размерностью (1, 7):

In [ ]:
y = torch.rand(1,7)
z = x_tensor @ y.T #use transparent for correct size
describe (z)

Type: torch.FloatTensor
Shape/Size: torch.Size([7, 1])
Values: 
tensor([[1.5776],
        [2.4745],
        [1.5299],
        [2.9080],
        [1.1338],
        [1.9929],
        [1.4187]])


In [ ]:

#something about commutativity

y @ x_tensor

tensor([[1.8925, 2.1995, 1.9848, 1.3441, 1.9241, 2.4077, 2.0041]])

3. Найдите максимум, минимум и среднее значение для полученного тензора (шаг 2):

In [ ]:
print ("maximum:{},\nminimum: {},\nmean: {}".
       format (torch.max(z), torch.min(z), torch.mean(z)))

maximum:2.9079947471618652,
minimum: 1.1338225603103638,
mean: 1.8621995449066162


4. Найдите индекс максимального и минимального значения для тензора, полученного в шаге 2:

In [ ]:
print ("index of maximum:{},\nindex of minimum :{}".
      format (torch.argmax(z), torch.argmin(z)))

index of maximum:3,
index of minimum :4


5. Найдите обратную матрицу (тензор), для матрицы (тензора) полученного на шаге 1:

In [40]:
#function for inv.matrix by pytorch and check our result
def matr_inv_tensor (x_tensor, n):
    try:
        x_inv = torch.linalg.inv(x_tensor)
        print (x_inv)
        print ("check results (results is good if above 0):{}".
                       format (torch.dist( x_tensor @ x_inv, torch.eye(n))))
    except RuntimeError:
        print ("the matrix x_tensor or any matrix in the batch of this matrices is not invertible")

In [41]:
matr_inv_tensor(x_tensor, 7)

tensor([[-3.8722, -2.1225, -2.3335,  1.8882,  2.7554,  2.3955,  1.7429],
        [ 3.2184,  2.5163,  2.4134, -1.4395, -1.7560, -3.2014, -1.2320],
        [-8.8330, -5.5236, -3.6086,  5.0020,  8.1562,  4.7829,  0.4463],
        [ 5.4388,  3.6867,  4.8734, -3.3631, -4.7218, -4.0086, -0.9657],
        [-5.6725, -3.2435, -3.7500,  2.4474,  5.5112,  4.1288,  1.0306],
        [ 2.4540,  0.3113, -0.4323, -0.8009, -1.8616, -0.1304,  0.7290],
        [ 8.1870,  5.3253,  4.3964, -3.9566, -8.4684, -4.4471, -1.8204]])
check results (results is good if above 0):1.8622109791976982e-06
