In [1]:
import torch

In [2]:
# function with information about tensor
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/Size: {}".format(x.shape))
    print("Values: \n{}".format(x))

1.Создайте двумерный тензор, после чего добавьте в него новое измерение размером 1 перед измерением 0:

In [3]:
x = torch.Tensor (5,6)
x_unsq= torch.unsqueeze(x, 0)
x_unsq.shape, x.shape

(torch.Size([1, 5, 6]), torch.Size([5, 6]))

In [4]:

# second variant
y = torch.Tensor (2,3)
y_unsq= torch.reshape(y, (1,2,3))
y_unsq.shape, y.shape

(torch.Size([1, 2, 3]), torch.Size([2, 3]))

2. Удалите дополнительное измерение, которое вы создали в шаге 1:

In [5]:
x_old_shape = torch.squeeze(x_unsq)
x_old_shape.shape

torch.Size([5, 6])

In [6]:
y_old_shape = torch.reshape(y_unsq, (2,3))
y_old_shape.shape

torch.Size([2, 3])

3. Создайте случайный тензор формы 5 на 3 в интервале [3, 7):

In [7]:

# usually dtype is torch.float64, but in this case it's too much
y = torch.randint(3,7,(5,3), dtype = torch.float32)
describe (y)

Type: torch.FloatTensor
Shape/Size: torch.Size([5, 3])
Values: 
tensor([[5., 4., 5.],
        [6., 4., 5.],
        [6., 3., 6.],
        [4., 4., 5.],
        [5., 3., 5.]])


4. Создайте тензор со значениями, взятыми из нормального распределения (матожидание = 0, стандартное отклонение = 1):

In [8]:
z = torch.randn (3,2)
describe (z)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 2])
Values: 
tensor([[-1.2115, -0.4522],
        [-1.0167, -1.0116],
        [ 0.6416, -0.2685]])


5. Извлеките индексы всех ненулевых элементов из тензора torch.Tensor([1, 1, 1, 0, 1]):

In [9]:
a = torch.Tensor([1, 1, 1, 0, 1])
torch.argwhere(a)

tensor([[0],
        [1],
        [2],
        [4]])

6. Создайте случайный тензор размерности (3, 1) а затем горизонтально разместите в ряд четыре его копии:

In [10]:
# may be I didn't get task
c = torch.Tensor (3,1)
torch.stack((c, c, c, c), dim=1)

tensor([[[1.0767e+09],
         [1.0767e+09],
         [1.0767e+09],
         [1.0767e+09]],

        [[3.0997e-41],
         [3.0997e-41],
         [3.0997e-41],
         [3.0997e-41]],

        [[1.0746e+09],
         [1.0746e+09],
         [1.0746e+09],
         [1.0746e+09]]])

In [11]:
torch.column_stack((c,c,c,c))

tensor([[1.0767e+09, 1.0767e+09, 1.0767e+09, 1.0767e+09],
        [3.0997e-41, 3.0997e-41, 3.0997e-41, 3.0997e-41],
        [1.0746e+09, 1.0746e+09, 1.0746e+09, 1.0746e+09]])

In [12]:
torch.hstack((c,c,c,c))

tensor([[1.0767e+09, 1.0767e+09, 1.0767e+09, 1.0767e+09],
        [3.0997e-41, 3.0997e-41, 3.0997e-41, 3.0997e-41],
        [1.0746e+09, 1.0746e+09, 1.0746e+09, 1.0746e+09]])

In [13]:
torch.cat ([c,c,c,c], dim = 1)

tensor([[1.0767e+09, 1.0767e+09, 1.0767e+09, 1.0767e+09],
        [3.0997e-41, 3.0997e-41, 3.0997e-41, 3.0997e-41],
        [1.0746e+09, 1.0746e+09, 1.0746e+09, 1.0746e+09]])

7. Верните пакетное произведение 2 трехмерных матриц (a = torch.rand(3,4,5) и b = torch.rand(3, 5, 4)):

In [14]:
a = torch.rand(3,4,5)
b = torch.rand(3,5,4)
C = torch.matmul(a,b)
describe (C)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 4, 4])
Values: 
tensor([[[1.2218, 1.5661, 1.2502, 1.4055],
         [0.7296, 0.9297, 1.1597, 1.4179],
         [1.8522, 2.2941, 2.1382, 2.2015],
         [1.1938, 1.4296, 1.2717, 1.8551]],

        [[1.1876, 0.8817, 1.0069, 0.4785],
         [1.3892, 1.2281, 1.2296, 1.2151],
         [1.1815, 1.0452, 0.8949, 1.0603],
         [1.0569, 1.0403, 0.9252, 1.1214]],

        [[2.4258, 1.7061, 1.8017, 1.3357],
         [1.6561, 1.1344, 1.0808, 0.7755],
         [2.1437, 1.3467, 1.7809, 1.1918],
         [2.0662, 1.3019, 1.8443, 1.5514]]])


8. Верните пакетное произведение трехмерной и двумерной матриц (a = torch.rand(3, 4, 5) и b = torch.rand(5,4)):

In [15]:
a = torch.rand (3,4,5)
b = torch.rand (5,4)
c = torch.matmul (a,b)
describe (c)

Type: torch.FloatTensor
Shape/Size: torch.Size([3, 4, 4])
Values: 
tensor([[[0.6884, 0.5340, 0.4731, 0.3532],
         [1.1308, 1.1201, 1.0568, 0.7870],
         [0.6675, 1.0162, 0.9174, 1.2683],
         [0.4095, 0.6808, 0.6007, 0.7162]],

        [[0.9486, 0.9446, 0.8012, 1.0014],
         [1.6694, 1.5288, 0.9242, 1.7225],
         [0.5332, 0.7433, 0.5823, 1.0157],
         [1.2324, 1.2719, 1.2029, 1.2290]],

        [[1.1045, 1.1080, 0.6918, 0.8487],
         [1.7828, 1.5841, 1.1747, 1.4460],
         [1.2515, 1.0964, 0.6285, 1.2206],
         [0.7818, 0.9007, 0.7943, 0.7447]]])


Вторая часть практики.

1. Создайте случайный тензор размерности (7,7):

In [47]:
x_tensor = torch.Tensor(7,7)
describe (x_tensor)

Type: torch.FloatTensor
Shape/Size: torch.Size([7, 7])
Values: 
tensor([[1.8776e+32, 4.3237e-41, 1.8776e+32, 4.3237e-41, 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 1.8788e+31, 1.7220e+22, 2.1715e-18,
         2.6428e+20],
        [1.3542e-05, 8.1933e-10, 4.4159e-05, 2.6661e-09, 3.4305e-06, 2.5932e-09,
         2.6516e-09],
        [4.3004e-05, 1.4580e-19, 1.1495e+24, 3.0881e+29, 1.5766e-19, 7.3313e+22,
         7.2151e+22],
        [2.8404e+29, 2.3089e-12, 1.9421e+31, 2.7491e+20, 6.1949e-04, 1.9421e+31,
         2.7491e+20],
        [2.3078e-12, 7.1760e+22, 7.2250e+28, 1.5766e-19, 5.4717e+22, 3.3091e+21,
         2.1119e+20],
        [1.7474e-04, 1.0921e-05, 2.1650e+23, 1.0501e-08, 2.7451e-06, 2.3076e-12,
         2.6302e+20]])


2. Определите операцию матричного умножения на тензоре с шага 1 с любым случайным тензором с размерностью (1, 7):

In [49]:
y = torch.rand(1,7)
z = x_tensor @ y.T #use transparent for correct size
describe (z)

Type: torch.FloatTensor
Shape/Size: torch.Size([7, 1])
Values: 
tensor([[2.2935e+32],
        [7.8846e+29],
        [3.6056e-05],
        [1.2961e+28],
        [1.3722e+31],
        [4.5870e+28],
        [1.3759e+23]])


In [50]:

#something about commutativity

y @ x_tensor

tensor([[1.1015e+32, 4.5275e+21, 1.1057e+32, 6.2480e+30, 9.1669e+21, 4.2120e+29,
         3.2723e+21]])

3. Найдите максимум, минимум и среднее значение для полученного тензора (шаг 2):

In [51]:
print ("maximum:{},\nminimum: {},\nmean: {}".
       format (torch.max(z), torch.min(z), torch.mean(z)))

maximum:2.2935264816526144e+32,
minimum: 3.605608799261972e-05,
mean: 3.484601737828109e+31


4. Найдите индекс максимального и минимального значения для тензора, полученного в шаге 2:

In [52]:
print ("index of maximum:{},\nindex of minimum :{}".
      format (torch.argmax(z), torch.argmin(z)))

index of maximum:0,
index of minimum :2


5. Найдите обратную матрицу (тензор), для матрицы (тензора) полученного на шаге 1:

In [56]:
x_inv = torch.linalg.inv(x_tensor)
describe (x_inv)

Type: torch.FloatTensor
Shape/Size: torch.Size([7, 7])
Values: 
tensor([[ 5.3259e-33, -2.8158e-28,  1.4101e+00,  1.7131e-26, -6.4667e-35,
         -1.6143e-32, -4.6991e-24],
        [ 1.1820e-32, -2.8355e-22,  1.2011e+06,  1.7251e-20, -6.5122e-29,
          1.3922e-23, -4.7319e-18],
        [ 4.3309e-39,  2.8158e-28, -1.4101e+00, -1.7131e-26,  6.4667e-35,
          1.6143e-32,  4.6991e-24],
        [ 1.9272e-41,  5.3170e-32, -2.6694e-04,  3.4478e-33, -1.2980e-41,
          3.0478e-36, -9.9653e-31],
        [-2.1027e-32,  6.5388e-26,  2.9123e+05, -3.9781e-24,  1.4979e-32,
         -3.3251e-27,  1.0883e-21],
        [-7.7897e-35, -2.7746e-28,  1.3923e+00,  1.6880e-26,  5.1426e-32,
         -1.5912e-32, -4.6303e-24],
        [-3.4039e-36, -2.3177e-25,  1.1637e+03,  1.4101e-23, -5.3229e-32,
         -1.3286e-29, -6.5897e-23]])


In [62]:
#check our result, for result above 0 right
torch.dist(x_tensor @ x_inv, torch.eye(7))

tensor(inf)

In [63]:
 #for case error we have to check.det for matrix.
#torch.linalg.det(x_tensor)
#if .det is 0, inv matrix isn't in real